### PR TITLE
unify code style, better typings, improved project template

### PR DESCRIPTION
**Pull request by e-cloud**
1. use ng lint --fix to fix most of code style base on tslint.json
2. manually fix some errors throwed by tslint and typescript.

Main Changes:
* normalize quote usage to double quotes
* order imports and add whitespace to import statements
* add method overloads for some pipes to comfort the compiler
* add some tslint disable comments for some code to avoid bigger change
* add a script to lint code
* add necessary peer dependencies
* upgrade most of deps
* upgrade the project config with latest angular-cli

### CODE REVIEW

**Comment by danrevah** [comment]
Looks like a great pull-request, Thanks!
I will go over it and see that everything is fine later.

For now, can you please replace the double-quite to single-quote as this is the standard I would like to follow?

**Comment by e-cloud** [comment]
sure

**Comment by danrevah** [comment]
Merged and now released as part of v1.7.0

**Comment by e-cloud** [comment]
How about #84? are going to accept it or reject, because it's the key problem why I submit PRs to this repo.

**Comment by danrevah** [comment]
about the folder changes it's a bit problemetic since it will cause a breaking change and a lot of repo's will start failing. can you change it to keep the folder hierarchy?

**Comment by e-cloud** [comment]
I think the folder change is a small problem. Without it, the new package tool will only generate Angular Package Format related code. No more plain source code will be published. That's the key breaking change.

**Pull request merged**
