### PR TITLE
Range Pipe

### PR DESCRIPTION
**Pull request by Albejr**
Suggestion of a new pipe to fill arrays.

### CODE REVIEW

**Comment by danrevah** [comment]
Seems like a good general pipe that might be useful.
We would need documentation in the `README.md` file as well before I could merge this.

**Comment by danrevah** [comment]
What about the review ? Can you also take care of the review request I wrote in the code?

**Comment by Albejr** [comment]
I did not understand the question (or I did not find the review). About documentation .md? I have added.

**Comment by danrevah** [comment]
It's about the pipe code:

"it can be more elegant with this kind of return (dropping the next variable):

```typescript
Array(count).fill().map((v, i) => step * i + start);
```"

**Comment by Albejr** [comment]
Certainly! I'll run new tests.

**Comment by Albejr** [comment]
This works, but the FILL method expects a parameter.

**Pull request merged**
