### PR TITLE
Implement ChunkPipe for chunking arrays

### PR DESCRIPTION
**Pull request by vdurante**

### CODE REVIEW

**Comment by vdurante** [comment]
@danrevah sorry to bother. Any reason why?

**Comment by danrevah** [comment]
It did not have an issue with a feature request to discuss first, after re-examining the pull-request it really seems like a good idea to add this pipe.

Thanks.

**Comment by vdurante** [comment]
@danrevah thank you! I appreciate your reconsideration. I will open an issue for discussion next time.

**Comment by danrevah** [comment]
@vdurante thank you for your contribution :) 

BTW you were missing an import/export at `array/index.ts`, I already took care of that and it was now deployed to NPM. (v2.4.7)

If you want to see what I mean:
https://github.com/danrevah/ngx-pipes/commit/378f576b1b338481eaa2ef91c67b20147634c5fc

**Pull request merged**
