### PR TITLE
Update to angular 13

### PR DESCRIPTION
**Pull request by biutas**
TODO: Update package.json version and fix karma tests (404 err)

### CODE REVIEW

**Comment by biutas** [comment]
What you think about bump version to number to match angular? So should be easier to know what version i should install depending on my angular version.

**Comment by pavankjadda** [comment]
@danrevah any plans to merge this?

**Review by pavankjadda — APPROVED** [review]

**Comment by biutas** [comment]
@danrevah can you review this?

**Comment by danrevah** [comment]
Can you explain what's the motivation behind it? Is it causing any failures with Angular 13?

**Comment by pavankjadda** [comment]
@danrevah Angular 13 dropped support for **ViewEngine**. In my projects all other libraries updated to Angular 13 with Ivy compilation. It would be nice if you can approve the PR and make it Angular 13 compatible.

**Comment by danrevah** [comment]
Done and published as part of v2.7.7

**Comment by pavankjadda** [comment]
> Done and published as part of v2.7.7
> 
> Thank you!

Thanks. BTW I still see latest release from 2018 in GitHub.

**Comment by pavankjadda** [comment]
Never mind. I see latest version in NPM, it seems you haven't created new release in GitHub. But that's okay. Thanks again

**Comment by danrevah** [comment]
Reverted due to previous version mismatch:
https://github.com/danrevah/ngx-pipes/issues/213

Angular 13 is now supported via Ngx-Pipes version v3.

**Pull request merged**
